# Generated by Django 3.1.3 on 2020-12-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_blog_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobileno',
            field=models.CharField(max_length=15),
        ),
    ]
